export const ROADMAP = [
  { day: 1, month: 1, dsa: 'Arrays - Intro & Traversal', aiml: 'What is ML?' },
  { day: 2, month: 1, dsa: 'Arrays - Prefix Sum', aiml: 'Types of ML (Supervised/Unsupervised)' },
  { day: 3, month: 1, dsa: 'Arrays - Two Pointers', aiml: 'ML Workflow & Pipeline' },
  { day: 4, month: 1, dsa: 'Arrays - Kadane Algorithm', aiml: 'Setting up Python + Jupyter' },
  { day: 5, month: 1, dsa: 'Arrays - Sliding Window', aiml: 'Intro to NumPy' },
  { day: 6, month: 1, dsa: 'Arrays - Practice Day', aiml: 'NumPy Arrays & Operations' },
  { day: 7, month: 1, dsa: 'Arrays - Mock Test', aiml: 'NumPy Broadcasting' },
  { day: 8, month: 1, dsa: 'Strings - Basics', aiml: 'Intro to Pandas' },
  { day: 9, month: 1, dsa: 'Strings - Pattern Matching', aiml: 'Pandas Series' },
  { day: 10, month: 1, dsa: 'Strings - Palindromes', aiml: 'Pandas DataFrames' },
  { day: 11, month: 1, dsa: 'Strings - Anagrams', aiml: 'Data Cleaning with Pandas' },
  { day: 12, month: 1, dsa: 'Strings - KMP Algorithm', aiml: 'GroupBy & Aggregation' },
  { day: 13, month: 1, dsa: 'Strings - Practice', aiml: 'Pandas Merge/Join' },
  { day: 14, month: 1, dsa: 'Strings - Mock Test', aiml: 'EDA Project Mini' },
  { day: 15, month: 1, dsa: 'Sorting - Bubble/Selection', aiml: 'Matplotlib Basics' },
  { day: 16, month: 1, dsa: 'Sorting - Merge Sort', aiml: 'Seaborn Visualization' },
  { day: 17, month: 1, dsa: 'Sorting - Quick Sort', aiml: 'Statistics Refresher' },
  { day: 18, month: 1, dsa: 'Searching - Binary Search', aiml: 'Probability Basics' },
  { day: 19, month: 1, dsa: 'Binary Search on Answer', aiml: 'Descriptive Statistics' },
  { day: 20, month: 1, dsa: 'Sort/Search - Practice', aiml: 'Hypothesis Testing' },
  { day: 21, month: 1, dsa: 'Sort/Search - Mock Test', aiml: 'Mini Statistics Quiz' },
  { day: 22, month: 1, dsa: 'Linked List - Intro', aiml: 'Vectors & Matrices' },
  { day: 23, month: 1, dsa: 'LL - Reverse/Detect Cycle', aiml: 'Matrix Operations' },
  { day: 24, month: 1, dsa: 'Doubly Linked List', aiml: 'Eigenvalues Intro' },
  { day: 25, month: 1, dsa: 'Stack - Implementation', aiml: 'Calculus for ML' },
  { day: 26, month: 1, dsa: 'Stack - Problems', aiml: 'Gradients & Derivatives' },
  { day: 27, month: 1, dsa: 'Queue + Deque', aiml: 'ML Math Recap' },
  { day: 28, month: 1, dsa: 'Stack/Queue Mock', aiml: 'Mini ML Project' },
  { day: 29, month: 1, dsa: 'Revision Day', aiml: 'Revision Day' },
  { day: 30, month: 1, dsa: 'Month 1 Final Test', aiml: 'Month 1 Final Quiz' },
  { day: 31, month: 2, dsa: 'Binary Tree - Intro', aiml: 'Linear Regression' },
  { day: 32, month: 2, dsa: 'Tree Traversals', aiml: 'Cost Function & MSE' },
  { day: 33, month: 2, dsa: 'BST Operations', aiml: 'Gradient Descent' },
  { day: 34, month: 2, dsa: 'Tree Views', aiml: 'Multiple Linear Regression' },
  { day: 35, month: 2, dsa: 'LCA + Diameter', aiml: 'Polynomial Regression' },
  { day: 36, month: 2, dsa: 'AVL & Heap Intro', aiml: 'Regularization (L1/L2)' },
  { day: 37, month: 2, dsa: 'Tree Mock Test', aiml: 'Regression Project' },
  { day: 38, month: 2, dsa: 'Graph Representation', aiml: 'Logistic Regression' },
  { day: 39, month: 2, dsa: 'BFS Traversal', aiml: 'Confusion Matrix' },
  { day: 40, month: 2, dsa: 'DFS Traversal', aiml: 'KNN Classifier' },
  { day: 41, month: 2, dsa: 'Topological Sort', aiml: 'Decision Trees' },
  { day: 42, month: 2, dsa: 'Dijkstra Algorithm', aiml: 'Random Forest' },
  { day: 43, month: 2, dsa: 'MST - Kruskal/Prim', aiml: 'SVM Intro' },
  { day: 44, month: 2, dsa: 'Graph Mock Test', aiml: 'Classification Project' },
  { day: 45, month: 2, dsa: 'DP - Intro & Memoization', aiml: 'Perceptron Model' },
  { day: 46, month: 2, dsa: 'DP - 1D Problems', aiml: 'Activation Functions' },
  { day: 47, month: 2, dsa: 'DP - Knapsack', aiml: 'Forward Propagation' },
  { day: 48, month: 2, dsa: 'DP - LIS/LCS', aiml: 'Backpropagation' },
  { day: 49, month: 2, dsa: 'DP - Grid Problems', aiml: 'Building NN with Keras' },
  { day: 50, month: 2, dsa: 'DP - Matrix Chain', aiml: 'CNN Intro' },
  { day: 51, month: 2, dsa: 'DP Mock Test', aiml: 'Image Classification Demo' },
  { day: 52, month: 2, dsa: 'Greedy Algorithms', aiml: 'RNN Intro' },
  { day: 53, month: 2, dsa: 'Bit Manipulation', aiml: 'NLP Basics' },
  { day: 54, month: 2, dsa: 'Tries', aiml: 'Word Embeddings' },
  { day: 55, month: 2, dsa: 'Segment Trees', aiml: 'Transformers Intro' },
  { day: 56, month: 2, dsa: 'System Design Basics', aiml: 'ML Deployment' },
  { day: 57, month: 2, dsa: 'Revision - Arrays/Strings', aiml: 'Capstone Project Part 1' },
  { day: 58, month: 2, dsa: 'Revision - Trees/Graphs', aiml: 'Capstone Project Part 2' },
  { day: 59, month: 2, dsa: 'Revision - DP', aiml: 'Capstone Project Part 3' },
  { day: 60, month: 2, dsa: 'Final Mock Interview', aiml: 'Capstone Presentation' },
];

export const DEFAULT_RESOURCES = [
  { title: 'Striver A-Z DSA Sheet', link: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/', source: 'Striver', category: 'DSA' },
  { title: 'GFG DSA Self Paced', link: 'https://www.geeksforgeeks.org/data-structures/', source: 'GFG', category: 'DSA' },
  { title: 'CodeWithHarry DSA Playlist', link: 'https://www.youtube.com/@CodeWithHarry', source: 'CodeWithHarry', category: 'DSA' },
  { title: 'Shraddha Khapra DSA C++', link: 'https://www.youtube.com/@ShradhaKhapra', source: 'ShraddhaKhapra', category: 'DSA' },
  { title: 'CampusX ML 100 Days', link: 'https://www.youtube.com/@campusx-official', source: 'CampusX', category: 'AI/ML' },
  { title: 'CodeBasics ML Playlist', link: 'https://www.youtube.com/@codebasics', source: 'CodeBasics', category: 'AI/ML' },
];
